Bug fix : Timeout in case of InvalidInstanceID.NotFound exception on Amazon
- The logic was changed to handle the case where AWS does
  not acknowledge the existence of new Instances
  immediately.

- However, the thread was stuck and not really exiting from
  the error block resulting in a timeout.

- Creating another task checker thread to avert the issue.

Symptoms of the issue are noted in the logs as below:
(The test times out after 10 minutes of hitting this
error block)

04:44:34
[38][W][1465472674108][41857/provisioning/aws/instance-adapter][onError][Could
not retrieve status for instance i-06a75d53674b2be38.
Retrying... Exception on AWS is
com.amazonaws.AmazonServiceException: The instance ID
'i-06a75d53674b2be38' does not exist (Service: AmazonEC2;
Status Code: 400; Error Code: InvalidInstanceID.NotFound;
Request ID: 19682226-afa2-446d-b9f0-eaf81d26cdfa)] 04:54:32
[39][I][1465473272496][41857][waitForTaskCompletion][Pending
task:
04:54:32
/provisioning/compute-tasks/d40747ba-0560-40c4-8c2b-d433d1b83350]
04:54:32 [40][I][1465473272497][41857][tearDown][Deleting 0
instance created from the test ]

Change-Id: I69917e82ffa052b4cdbb87706e20b336725d37ec